backend:
  name: git-gateway
  branch: master
  repo: RolandRFuchs92/gatsby-netlify-cms-ts

media_folder: /src/images
public_folder: /img

collections:
  - name: "homePage"
    label: "Home page"
    files:
      - label: "Landing Screen"
        name: "landingScreen"
        file: "content/home/landingScreen.md"
        fields:
          - {
              label: "Landing screen Image",
              name: "landingImage",
              widget: "image",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
      - name: "sitecss"
        label: "Site Css"
        file: "content/home/styles.json"
        fields:
          - {
              label: "Css",
              name: "styles",
              widget: "code",
              default_language: "css",
            }
      - label: "Orders And Collections"
        name: "ordersAndCollections"
        file: "content/home/ordersAndCollections.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string" }
          - {
              label: "Image",
              name: "image",
              widget: "image",
              default: "src/images/ordersAndCollections.jpg",
              allow_multiple: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "products"
    label: "Products"
    folder: "content/home/products"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
